export const howItWorksPage = {
  metaTitle: "How It Works",
  metaDescription: "A clear explanation of how LOTACHI is designed to connect model opportunities with the right people.",
  eyebrow: "How It Works",
  heading: "From opportunity to appointment.",
  intro:
    "This is how LOTACHI is designed to work as the platform develops. Each step below is labelled with where it stands today: available now, part of what we're testing during the pilot, or planned for later.",
  stageLegend: [
    { stage: "available", label: "Available now", body: "Live today — you can do this as soon as you join." },
    { stage: "pilot", label: "Pilot", body: "Happening manually, on a case-by-case basis, while we test the workflow." },
    { stage: "future", label: "Planned", body: "Not built yet. Described here so you know where things are heading." },
  ],
  steps: [
    {
      number: "01",
      title: "Opportunity created",
      body: "A provider tells LOTACHI about the session they need models for — category, requirements and timing.",
      stage: "pilot",
    },
    {
      number: "02",
      title: "Model requirements added",
      body: "The provider sets out requirements for the opportunity — category, eligibility, pricing, duration, and whether photos or video are involved and what they'd be used for.",
      stage: "pilot",
    },
    {
      number: "03",
      title: "Relevant models discover the opportunity",
      body: "During the pilot, we manually introduce opportunities to people who match on category, location and availability, drawing on preferences collected at sign-up.",
      stage: "pilot",
    },
    {
      number: "04",
      title: "Potential eligibility and match",
      body: "LOTACHI helps surface potentially suitable people based on the information provided — this is a manual step during the pilot, not an automated decision.",
      stage: "pilot",
    },
    {
      number: "05",
      title: "Provider confirms suitability where required",
      body: "Where professional or clinical judgement is needed, the provider confirms suitability directly — this is not a decision LOTACHI makes, now or later.",
      stage: "pilot",
    },
    {
      number: "06",
      title: "Booking",
      body: "Structured, in-platform booking is planned. During the pilot, LOTACHI introduces you and the provider confirms the appointment. If the opportunity has a price, you pay the provider directly — LOTACHI doesn't take payment for treatments.",
      stage: "pilot",
    },
    {
      number: "07",
      title: "Attendance",
      body: "The model attends the session with the provider, who remains responsible for delivery. Any photo or video consent is requested separately from treatment consent, never combined with it. The provider then confirms your attendance to LOTACHI.",
      stage: "pilot",
    },
    {
      number: "08",
      title: "Aftercare and after-appointment contact",
      body: "Once booking functionality exists, the provider will attach their own written aftercare to the completed booking, along with a clear way to contact them afterwards if there's a concern. This is planned, not live today.",
      stage: "future",
    },
  ],
  note: "Where a step involves professional or clinical judgement, LOTACHI refers to people as 'potentially suitable' or 'potentially eligible' — the final decision sits with the provider. LOTACHI does not infer suitability from appearance, and never writes aftercare content on a provider's behalf.",
  forModels: {
    heading: "For Chi Chis",
    opportunityTypesHeading: "Opportunities may include",
    opportunityTypes: [
      "Free services",
      "Discounted services",
      "Last-minute opportunities",
      "Training sessions",
      "Demonstrations",
      "Portfolio opportunities",
    ],
    caveatsHeading: "Worth knowing",
    caveats: [
      "Availability varies by location, category and provider.",
      "Provider eligibility requirements still apply.",
      "LOTACHI does not make clinical suitability decisions — that remains with the provider.",
    ],
  },
  forProviders: {
    heading: "For providers",
    audiencesHeading: "Being designed for",
    audiences: [
      "Training academies",
      "Colleges",
      "Salons",
      "Clinics",
      "Educators",
      "Newly qualified professionals",
      "Practitioners building portfolios",
      "Organisations running practical training",
    ],
  },
};
